// Мок /api/* и SSE для проверки вёрстки без шлюза. ?state=run|wait|idle
(() => {
  const state = new URLSearchParams(location.search).get('state') || 'run';
  const now = Date.now(), iso = ms => new Date(now - ms).toISOString();
  const start = { promptPreview: 'Проверь монитор по гайдам modern-web-guidance и предложи исправления', sessionId: '0f3c9a1e-1111-2222-3333-444455556666', model: 'claude-opus-5', permissionMode: 'default', effort: 'high' };
  const steps = Array.from({ length: 12 }, (_, i) => ({ at: iso(60000 - i * 4000), description: `Read src/Features/Monitor/index.html строка ${i * 40}`, nested: i % 4 === 3 }));
  const run = state === 'idle' ? null : { start, startedUtc: iso(65000), toolCalls: 14, steps, droppedSteps: 2 };
  const approvals = state === 'wait' ? [{ tool: 'Bash', brief: 'git push origin main', sinceUtc: iso(20000) }] : [];
  const snapshot = { at: new Date(now).toISOString(), gatewayStartedUtc: iso(3600 * 1000 * 5), agent: 'Claude Code', cliVersion: '2.1.261 (Claude Code)', project: 'C:\\Users\\me\\source\\repos\\ME\\AgentsTracker', model: null, permissionMode: 'default', effort: 'high', session: start.sessionId, run, approvals, queue: state === 'run' ? ['ещё один запрос', '/simplify'] : [], isBusy: state !== 'idle' };
  const days = Array.from({ length: 20 }, (_, i) => ({ day: new Date(now - (19 - i) * 86400000).toISOString().slice(0, 10), runs: 1 + (i * 7) % 9, inputTokens: 20000 * i, outputTokens: 3000 * i, durationMs: 60000 * (1 + i % 5) }));
  const runs = Array.from({ length: 15 }, (_, i) => ({ startedUtc: iso(i * 5400000), projectPath: i % 3 ? 'C:\\repos\\ME\\AgentsTracker' : 'C:\\repos\\ME\\Other', prompt: 'Промпт номер ' + i + ' довольно длинный, чтобы проверить перенос строк в таблице запусков', outcome: ['ok', 'error', 'cancel', 'rate-limit'][i % 4], durationMs: 120000 + i * 9000, turns: 3 + i, toolCalls: 10 + i, inputTokens: 100000 + i * 1000, outputTokens: 5000, sessionId: start.sessionId }));
  const stats = { sinceUtc: iso(30 * 86400000), total: { runs: 88, turns: 512, inputTokens: 3.2e6, outputTokens: 4e5, cacheReadTokens: 2.9e6, durationMs: 9e6 }, byDay: days, byModel: [{ model: 'claude-opus-5', runs: 60, inputTokens: 2e6, outputTokens: 3e5, cacheReadTokens: 1.8e6 }], skills: [{ command: '/simplify', count: 9 }, { command: '/code-review', count: 4 }], sessions: [{ projectPath: 'C:\\repos\\ME\\AgentsTracker', id: start.sessionId, title: 'Аудит монитора', lastActivityUtc: iso(100000), turns: 12, active: true }] };
  const limits = { fetchedUtc: new Date(now).toISOString(), windows: [{ key: 'five_hour', used: 0.72, resetsAt: new Date(now + 5400000).toISOString() }, { key: 'seven_day', used: 0.35, resetsAt: new Date(now + 3 * 86400000).toISOString() }, { key: 'seven_day_opus', used: 0.9, resetsAt: new Date(now + 3 * 86400000).toISOString() }], extraUsageEnabled: false };
  const audit = Array.from({ length: 8 }, (_, i) => ({ at: iso(i * 60000), kind: ['run.start', 'approval', 'message'][i % 3], summary: 'Событие ' + i, outcome: 'ok', userKey: 'telegram:12345', project: 'AgentsTracker' }));
  const log = Array.from({ length: 8 }, (_, i) => ({ at: iso(i * 30000), level: ['Information', 'Warning', 'Error'][i % 3], category: 'Features.Chat.ChatWorker', message: 'Сообщение лога ' + i, exception: i === 2 ? 'System.Exception: boom\n   at X.Y()' : null }));
  const routes = { '/api/stats': stats, '/api/runs': runs, '/api/limits': limits, '/api/audit': audit, '/api/log': log };
  window.fetch = url => { const k = Object.keys(routes).find(r => String(url).startsWith(r)); return Promise.resolve({ ok: !!k, json: () => Promise.resolve(routes[k]) }); };
  window.EventSource = class { constructor() { setTimeout(() => { this.onopen?.(); this.h?.({ data: JSON.stringify(snapshot) }); }, 50); } addEventListener(t, h) { this.h = h; } };
})();
